fn main {
  try {
    println("Hello, world!")
  } catch {
    _ => println("Error")
  }
}
